name = "Theme"
license = "MIT"
licenselink = "https://github.com/ukaszg/theme/blob/master/LICENSE"
description = "Hugo theme."
homepage = "https://github.com/ukaszg/theme/"
tags = ["blog", "plain", "blank", "starter", "development"]
features = ["blog"]
min_version = "0.20"

[author]
  name = "ukaszg"
  homepage = "https://github.com/ukaszg"

[original]
  name = "Blank"
  author = "Vimux"
  homepage = "https://github.com/vimux/blank/"
  repo = "https://github.com/vimux/blank/"
